// js/svg-manager.js
// Auto-generado desde Catalogo_Cuadrado_20x20_Simulador.xlsx
// Estructura esperada: assets/svg/<filename>

window.MOSAIC_MODELS = [
  { id: "adonia", name: "Adonia", filename: "adonia.svg", category: "CLASICOS", rotate: true },
  { id: "alberi", name: "Alberi", filename: "alberi.svg", category: "ORGANICOS", rotate: true },
  { id: "allegra", name: "Allegra", filename: "allegra.svg", category: "ORGANICOS", rotate: true },
  { id: "andalucia", name: "Andalucia", filename: "andalucia.svg", category: "ORGANICOS", rotate: true },
  { id: "anthea", name: "Anthea", filename: "anthea.svg", category: "MODERNOS", rotate: false },
  { id: "antica", name: "Antica", filename: "antica.svg", category: "CLASICOS", rotate: false },
  { id: "ares", name: "Ares", filename: "ares.svg", category: "GEOMETRICOS", rotate: false },
  { id: "atrani", name: "Atrani", filename: "atrani.svg", category: "GEOMETRICOS", rotate: false },
  { id: "aussie", name: "Aussie", filename: "aussie.svg", category: "GEOMETRICOS", rotate: false },
  { id: "baku", name: "Baku", filename: "baku.svg", category: "GEOMETRICOS", rotate: true },
  { id: "balandra", name: "Balandra", filename: "balandra.svg", category: "CLASICOS", rotate: true },
  { id: "barcelona-2", name: "Barcelona-2", filename: "barcelona-2.svg", category: "GEOMETRICOS", rotate: false },
  { id: "barcelona-4", name: "Barcelona-4", filename: "barcelona-4.svg", category: "GEOMETRICOS", rotate: false },
  { id: "baviera", name: "Baviera", filename: "baviera.svg", category: "CLASICOS", rotate: false },
  { id: "bizancio", name: "Bizancio", filename: "bizancio.svg", category: "CLASICOS", rotate: true },
  { id: "bizantino", name: "Bizantino", filename: "bizantino.svg", category: "CLASICOS", rotate: false },
  { id: "bizantino-carre", name: "Bizantino Carré", filename: "bizantino-carre.svg", category: "CLASICOS", rotate: true },
  { id: "bizantino-duplo", name: "Bizantino Duplo", filename: "bizantino-duplo.svg", category: "CLASICOS", rotate: false },
  { id: "bizantino-geant", name: "Bizantino Géant", filename: "bizantino-geant.svg", category: "CLASICOS", rotate: true },
  { id: "bizantino-grand", name: "Bizantino Grand", filename: "bizantino-grand.svg", category: "GEOMETRICOS", rotate: false },
  { id: "bizantino-meros", name: "Bizantino Meros", filename: "bizantino-meros.svg", category: "MODERNOS", rotate: true },
  { id: "bogota", name: "Bogotá", filename: "bogota.svg", category: "GEOMETRICOS", rotate: false },
  { id: "burdeos", name: "Burdeos", filename: "burdeos.svg", category: "GEOMETRICOS", rotate: true },
  { id: "campanello", name: "Campanello", filename: "campanello.svg", category: "CLASICOS", rotate: true },
  { id: "canea", name: "Canea", filename: "canea.svg", category: "CLASICOS", rotate: true },
  { id: "cardiff", name: "Cardiff", filename: "cardiff.svg", category: "CLASICOS", rotate: true },
  { id: "carpo", name: "Carpo", filename: "carpo.svg", category: "CLASICOS", rotate: true },
  { id: "carreau", name: "Carreau", filename: "carreau.svg", category: "CLASICOS", rotate: false },
  { id: "cerchio", name: "Cerchio", filename: "cerchio.svg", category: "MODERNOS", rotate: false },
  { id: "citadel", name: "Citadel", filename: "citadel.svg", category: "GEOMETRICOS", rotate: false },
  { id: "citadella", name: "Citadella", filename: "citadella.svg", category: "GEOMETRICOS", rotate: true },
  { id: "classique", name: "Classique", filename: "classique.svg", category: "FLORALES", rotate: true },
  { id: "clio", name: "Clio", filename: "clio.svg", category: "CLASICOS", rotate: true },
  { id: "clover", name: "Clover", filename: "clover.svg", category: "FLORALES", rotate: true },
  { id: "cosmo", name: "Cosmo", filename: "cosmo.svg", category: "CLASICOS", rotate: false },
  { id: "cosmos-grand", name: "Cosmos Grand", filename: "cosmos-grand.svg", category: "CLASICOS", rotate: false },
  { id: "cronos", name: "Cronos", filename: "cronos.svg", category: "CLASICOS", rotate: false },
  { id: "cubi-san-marcos", name: "Cubi San Marcos", filename: "cubi-san-marcos.svg", category: "GEOMETRICOS", rotate: false },
  { id: "dalia", name: "Dalía", filename: "dalia.svg", category: "FLORALES", rotate: true },
  { id: "denes", name: "Denes", filename: "denes.svg", category: "CLASICOS", rotate: true },
  { id: "dubai", name: "Dubai", filename: "dubai.svg", category: "MODERNOS", rotate: true },
  { id: "ellen", name: "Ellen", filename: "ellen.svg", category: "GEOMETRICOS", rotate: true },
  { id: "emilia", name: "Emilia", filename: "emilia.svg", category: "CLASICOS", rotate: false },
  { id: "felce", name: "Felce", filename: "felce.svg", category: "CLASICOS", rotate: true },
  { id: "fiore", name: "Fiore", filename: "fiore.svg", category: "FLORALES", rotate: false },
  { id: "fiorelli", name: "Fiorelli", filename: "fiorelli.svg", category: "FLORALES", rotate: false },
  { id: "fiorentine", name: "Fiorentine", filename: "fiorentine.svg", category: "FLORALES", rotate: true },
  { id: "graz", name: "Graz", filename: "graz.svg", category: "ORGANICOS", rotate: true },
  { id: "groningen", name: "Groningen", filename: "groningen.svg", category: "GEOMETRICOS", rotate: false },
  { id: "hacienda", name: "Hacienda", filename: "hacienda.svg", category: "GEOMETRICOS", rotate: true },
  { id: "hamsa", name: "Hamsa", filename: "hamsa.svg", category: "FLORALES", rotate: false },
  { id: "hermes", name: "Hermes", filename: "hermes.svg", category: "GEOMETRICOS", rotate: false },
  { id: "hoku", name: "Hoku", filename: "hoku.svg", category: "GEOMETRICOS", rotate: true },
  { id: "imaginni", name: "Imaginni", filename: "imaginni.svg", category: "GEOMETRICOS", rotate: false },
  { id: "imaginni-duo", name: "Imaginni Duo", filename: "imaginni-duo.svg", category: "GEOMETRICOS", rotate: false },
  { id: "itza", name: "Itza", filename: "itza.svg", category: "GEOMETRICOS", rotate: true },
  { id: "jinan", name: "Jinan", filename: "jinan.svg", category: "CLASICOS", rotate: false },
  { id: "kara", name: "Kara", filename: "kara.svg", category: "GEOMETRICOS", rotate: false },
  { id: "kenia", name: "Kenia", filename: "kenia.svg", category: "MODERNOS", rotate: true },
  { id: "kin", name: "Kin", filename: "kin.svg", category: "GEOMETRICOS", rotate: false },
  { id: "kona", name: "Kona", filename: "kona.svg", category: "GEOMETRICOS", rotate: true },
  { id: "kona-grand", name: "Kona Grand", filename: "kona-grand.svg", category: "MODERNOS", rotate: true },
  { id: "koren", name: "Koren", filename: "koren.svg", category: "CLASICOS", rotate: true },
  { id: "lauf", name: "Lauf", filename: "lauf.svg", category: "ORGANICOS", rotate: false },
  { id: "leiden", name: "Leiden", filename: "leiden.svg", category: "FLORALES", rotate: true },
  { id: "lux", name: "Lux", filename: "lux.svg", category: "MODERNOS", rotate: false },
  { id: "mallorca", name: "Mallorca", filename: "mallorca.svg", category: "FLORALES", rotate: true },
  { id: "marsella", name: "Marsella", filename: "marsella.svg", category: "CLASICOS", rotate: false },
  { id: "morocco", name: "Morocco", filename: "morocco.svg", category: "FLORALES", rotate: false },
  { id: "niza", name: "Niza", filename: "niza.svg", category: "CLASICOS", rotate: true },
  { id: "olesia", name: "Olesia", filename: "olesia.svg", category: "CLASICOS", rotate: true },
  { id: "olimpia", name: "Olimpia", filename: "olimpia.svg", category: "CLASICOS", rotate: false },
  { id: "palmanova", name: "Palmanova", filename: "palmanova.svg", category: "CLASICOS", rotate: false },
  { id: "passagi", name: "Passagi", filename: "passagi.svg", category: "GEOMETRICOS", rotate: false },
  { id: "pensilvania", name: "Pensilvania", filename: "pensilvania.svg", category: "GEOMETRICOS", rotate: false },
  { id: "perseo", name: "Perseo", filename: "perseo.svg", category: "CLASICOS", rotate: true },
  { id: "pianni", name: "Pianni", filename: "pianni.svg", category: "GEOMETRICOS", rotate: false },
  { id: "quadri", name: "Quadri", filename: "quadri.svg", category: "GEOMETRICOS", rotate: false },
  { id: "quadri-2", name: "Quadri", filename: "quadri-2.svg", category: "GEOMETRICOS", rotate: false },
  { id: "quadri-duplo", name: "Quadri Duplo", filename: "quadri-duplo.svg", category: "GEOMETRICOS", rotate: false },
  { id: "raggi-dos", name: "Raggi Dos", filename: "raggi-dos.svg", category: "GEOMETRICOS", rotate: true },
  { id: "raggi-uno", name: "Raggi Uno", filename: "raggi-uno.svg", category: "GEOMETRICOS", rotate: false },
  { id: "ravenna", name: "Ravenna", filename: "ravenna.svg", category: "CLASICOS", rotate: true },
  { id: "rhin", name: "Rhin", filename: "rhin.svg", category: "CLASICOS", rotate: true },
  { id: "romano", name: "Romano", filename: "romano.svg", category: "CLASICOS", rotate: true },
  { id: "sicilia", name: "Sicilia", filename: "sicilia.svg", category: "CLASICOS", rotate: true },
  { id: "sonata", name: "Sonata", filename: "sonata.svg", category: "MODERNOS", rotate: false },
  { id: "spatola", name: "Spatola", filename: "spatola.svg", category: "GEOMETRICOS", rotate: false },
  { id: "stella-milano", name: "Stella Milano", filename: "stella-milano.svg", category: "GEOMETRICOS", rotate: false },
  { id: "temara", name: "Temara", filename: "temara.svg", category: "FLORALES", rotate: true },
  { id: "terra", name: "Terra", filename: "terra.svg", category: "CLASICOS", rotate: false },
  { id: "thera", name: "Thera", filename: "thera.svg", category: "CLASICOS", rotate: false },
  { id: "tonatiuh", name: "Tonatiuh", filename: "tonatiuh.svg", category: "CLASICOS", rotate: true },
  { id: "tostapane", name: "Tostapane", filename: "tostapane.svg", category: "GEOMETRICOS", rotate: false },
  { id: "tunisia", name: "Tunisia", filename: "tunisia.svg", category: "FLORALES", rotate: false },
  { id: "turin", name: "Turin", filename: "turin.svg", category: "ORGANICOS", rotate: true },
  { id: "undam-dos", name: "Undam Dos", filename: "undam-dos.svg", category: "ORGANICOS", rotate: true },
  { id: "undam-uno", name: "Undam Uno", filename: "undam-uno.svg", category: "ORGANICOS", rotate: true },
  { id: "valentine", name: "Valentine", filename: "valentine.svg", category: "FLORALES", rotate: true },
  { id: "vecchio", name: "Vecchio", filename: "vecchio.svg", category: "CLASICOS", rotate: true },
  { id: "venecia", name: "Venecia", filename: "venecia.svg", category: "GEOMETRICOS", rotate: true },
  { id: "veneto", name: "Veneto", filename: "veneto.svg", category: "GEOMETRICOS", rotate: true },
  { id: "vera", name: "Vera", filename: "vera.svg", category: "GEOMETRICOS", rotate: true },
  { id: "verona", name: "Verona", filename: "verona.svg", category: "GEOMETRICOS", rotate: true },
  { id: "vicenza", name: "Vicenza", filename: "vicenza.svg", category: "GEOMETRICOS", rotate: true },
  { id: "xochi", name: "Xochi", filename: "xochi.svg", category: "FLORALES", rotate: true },
  { id: "zigzag", name: "Zigzag", filename: "zigzag.svg", category: "GEOMETRICOS", rotate: true },
];

window.getModelById = function(id){
  return (window.MOSAIC_MODELS || []).find(m => m.id === id) || null;
};

window.getModelUrl = function(model){
  if (!model) return "";
  return `assets/svg/${model.filename}`;
};

const __SVG_CACHE = new Map();
window.loadSvgText = async function(url){
  if (__SVG_CACHE.has(url)) return __SVG_CACHE.get(url);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`No se pudo cargar SVG: ${url} (${res.status})`);
  const text = await res.text();
  __SVG_CACHE.set(url, text);
  return text;
};